version: "3.8"
services:
  bot:
    build:
      context: ./bot
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: marat
      POSTGRES_PASSWORD: utyz@2005
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/14/main/
    ports:
      - "5432:5432"
volumes:
  db_data: